import type {
  Bot,
  Game,
  Listing,
  Notification,
  Order,
  Product,
  Rental,
  Review,
  Ticket,
  Transaction,
  User,
} from "@/types";

const seed = (i: number) => `https://images.unsplash.com/photo-${i}?w=600&q=80`;

export const MOCK_USERS: User[] = [
  {
    id: "u_1",
    username: "ShadowKing",
    email: "shadow@nexus.local",
    avatar: "https://avatars.githubusercontent.com/u/1?v=4",
    role: "USER",
    balance: 12500,
    verified: true,
    rating: 4.9,
    salesCount: 342,
    level: "GOLD",
    createdAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "u_2",
    username: "FrostMage",
    email: "frost@nexus.local",
    avatar: "https://avatars.githubusercontent.com/u/2?v=4",
    role: "USER",
    balance: 850,
    verified: true,
    rating: 4.6,
    salesCount: 88,
    level: "SILVER",
    createdAt: "2024-08-21T10:00:00Z",
  },
  {
    id: "u_admin",
    username: "admin",
    email: "admin@nexus.local",
    avatar: "https://avatars.githubusercontent.com/u/3?v=4",
    role: "ADMIN",
    balance: 0,
    verified: true,
    rating: 0,
    salesCount: 0,
    level: "BRONZE",
    createdAt: "2024-01-01T10:00:00Z",
  },
];

export const MOCK_GAMES: Game[] = [
  {
    id: "wow",
    name: "World of Warcraft",
    cover: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80",
    activeListings: 1240,
  },
  {
    id: "lol",
    name: "League of Legends",
    cover: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&q=80",
    activeListings: 890,
  },
  {
    id: "cs2",
    name: "Counter-Strike 2",
    cover: "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=800&q=80",
    activeListings: 4521,
  },
  {
    id: "dota",
    name: "Dota 2",
    cover: "https://images.unsplash.com/photo-1605647540924-852290f6b0d5?w=800&q=80",
    activeListings: 1124,
  },
  {
    id: "valorant",
    name: "Valorant",
    cover: "https://images.unsplash.com/photo-1542751110-97427bbecf20?w=800&q=80",
    activeListings: 763,
  },
  {
    id: "genshin",
    name: "Genshin Impact",
    cover: "https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=800&q=80",
    activeListings: 612,
  },
];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "l_1",
    title: "Аккаунт WoW Lich King 80lvl + Геар 285",
    price: 4500,
    currency: "₽",
    images: [seed(1542751371) + "&fit=crop"],
    seller: MOCK_USERS[0],
    game: "World of Warcraft",
    category: "Аккаунты",
    deliveryTime: "15 минут",
    rating: 4.9,
    reviews: 124,
    isHot: true,
  },
  {
    id: "l_2",
    title: "10 000 Gold — Stormrage US",
    price: 1280,
    currency: "₽",
    images: [seed(1518770660439)],
    seller: MOCK_USERS[1],
    game: "World of Warcraft",
    category: "Валюта",
    deliveryTime: "5 минут",
    rating: 5.0,
    reviews: 482,
    isHot: false,
  },
  {
    id: "l_3",
    title: "AWP | Asiimov (Field-Tested)",
    price: 7800,
    currency: "₽",
    images: [seed(1493711662062)],
    seller: MOCK_USERS[0],
    game: "Counter-Strike 2",
    category: "Скины",
    deliveryTime: "Мгновенно",
    rating: 4.8,
    reviews: 67,
    isHot: true,
  },
  {
    id: "l_4",
    title: "Прокачка Платина → Алмаз LoL",
    price: 2200,
    currency: "₽",
    images: [seed(1538481199705)],
    seller: MOCK_USERS[1],
    game: "League of Legends",
    category: "Прокачка",
    deliveryTime: "2-3 дня",
    rating: 4.7,
    reviews: 39,
    isHot: false,
  },
  {
    id: "l_5",
    title: "Архонт I — Калибровка готова",
    price: 3500,
    currency: "₽",
    images: [seed(1605647540924)],
    seller: MOCK_USERS[0],
    game: "Dota 2",
    category: "Аккаунты",
    deliveryTime: "30 минут",
    rating: 4.9,
    reviews: 91,
    isHot: false,
  },
  {
    id: "l_6",
    title: "Genesis Crystals 6480",
    price: 5990,
    currency: "₽",
    images: [seed(1551103782)],
    seller: MOCK_USERS[1],
    game: "Genshin Impact",
    category: "Валюта",
    deliveryTime: "1 час",
    rating: 4.6,
    reviews: 213,
    isHot: false,
  },
  {
    id: "l_7",
    title: "Valorant Points 5350 VP",
    price: 4290,
    currency: "₽",
    images: [seed(1542751110)],
    seller: MOCK_USERS[0],
    game: "Valorant",
    category: "Валюта",
    deliveryTime: "10 минут",
    rating: 4.8,
    reviews: 178,
    isHot: true,
  },
  {
    id: "l_8",
    title: "WoW: Wrath Boost 70-80",
    price: 1990,
    currency: "₽",
    images: [seed(1542751371)],
    seller: MOCK_USERS[1],
    game: "World of Warcraft",
    category: "Прокачка",
    deliveryTime: "2 дня",
    rating: 4.5,
    reviews: 24,
    isHot: false,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p_1",
    name: "Steam Wallet $50",
    description: "Цифровой код пополнения Steam-кошелька на 50 USD.",
    price: 4990,
    currency: "₽",
    images: [seed(1542751110)],
    category: "Ключи",
    isOfficial: true,
    deliveryType: "INSTANT",
    stock: -1,
    sold: 1820,
    isHot: true,
  },
  {
    id: "p_2",
    name: "Discord Nitro 1 месяц",
    description: "Подписка Discord Nitro с расширенными возможностями.",
    price: 690,
    currency: "₽",
    images: [seed(1611162617213)],
    category: "Подписки",
    isOfficial: true,
    deliveryType: "AUTO",
    stock: 200,
    sold: 540,
    isHot: false,
  },
  {
    id: "p_3",
    name: "PlayStation Plus Essential 12m",
    description: "Годовая подписка PS Plus Essential.",
    price: 4490,
    currency: "₽",
    images: [seed(1606144042614)],
    category: "Подписки",
    isOfficial: true,
    deliveryType: "MANUAL",
    stock: 35,
    sold: 312,
    isHot: false,
  },
  {
    id: "p_4",
    name: "Xbox Game Pass Ultimate 3m",
    description: "3 месяца Xbox Game Pass Ultimate — сотни игр.",
    price: 2790,
    currency: "₽",
    images: [seed(1592155931584)],
    category: "Подписки",
    isOfficial: true,
    deliveryType: "INSTANT",
    stock: 80,
    sold: 980,
    isHot: true,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "o_1",
    buyerId: "u_2",
    sellerId: "u_1",
    items: [{ name: "AWP | Asiimov (FT)", price: 7800, quantity: 1 }],
    subtotal: 7800,
    fee: 390,
    total: 8190,
    status: "COMPLETED",
    paymentStatus: "PAID",
    createdAt: "2026-04-30T14:22:00Z",
  },
  {
    id: "o_2",
    buyerId: "u_1",
    sellerId: "u_2",
    items: [{ name: "10 000 Gold — Stormrage", price: 1280, quantity: 2 }],
    subtotal: 2560,
    fee: 128,
    total: 2688,
    status: "DELIVERING",
    paymentStatus: "PAID",
    createdAt: "2026-05-04T09:11:00Z",
  },
  {
    id: "o_3",
    buyerId: "u_2",
    sellerId: "u_1",
    items: [{ name: "Steam Wallet $50", price: 4990, quantity: 1 }],
    subtotal: 4990,
    fee: 0,
    total: 4990,
    status: "PROCESSING",
    paymentStatus: "PAID",
    createdAt: "2026-05-05T08:00:00Z",
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "t_1",
    type: "DEPOSIT",
    amount: 5000,
    balance: 12500,
    description: "Пополнение картой ****4521",
    createdAt: "2026-05-01T10:11:00Z",
    status: "COMPLETED",
  },
  {
    id: "t_2",
    type: "SALE",
    amount: 7800,
    balance: 19420,
    description: "Продажа: AWP | Asiimov",
    createdAt: "2026-04-30T14:25:00Z",
    status: "COMPLETED",
  },
  {
    id: "t_3",
    type: "WITHDRAWAL",
    amount: -3000,
    balance: 9500,
    description: "Вывод на карту ****4521",
    createdAt: "2026-04-28T16:00:00Z",
    status: "COMPLETED",
  },
];

export const MOCK_BOTS: Bot[] = [
  {
    id: "b_1",
    name: "FunPay Auto-Reply",
    type: "FUNPAY",
    status: "RUNNING",
    uptime: 124820,
    messagesProcessed: 1284,
    salesCount: 41,
  },
  {
    id: "b_2",
    name: "Steam Trade Bot #1",
    type: "STEAM",
    status: "RUNNING",
    uptime: 84230,
    messagesProcessed: 218,
    salesCount: 12,
  },
  {
    id: "b_3",
    name: "Playerok Watcher",
    type: "PLAYEROK",
    status: "PAUSED",
    uptime: 0,
    messagesProcessed: 0,
    salesCount: 0,
  },
];

export const MOCK_RENTALS: Rental[] = [
  {
    id: "r_1",
    gameId: "cyberpunk",
    gameName: "Cyberpunk 2077",
    cover: seed(1542751110),
    pricePerDay: 89,
    pricePerWeek: 499,
    pricePerMonth: 1490,
    isAvailable: true,
  },
  {
    id: "r_2",
    gameId: "rdr2",
    gameName: "Red Dead Redemption 2",
    cover: seed(1538481199705),
    pricePerDay: 99,
    pricePerWeek: 599,
    pricePerMonth: 1690,
    isAvailable: true,
  },
  {
    id: "r_3",
    gameId: "elden",
    gameName: "Elden Ring",
    cover: seed(1605647540924),
    pricePerDay: 119,
    pricePerWeek: 699,
    pricePerMonth: 1990,
    isAvailable: false,
  },
];

export const MOCK_TICKETS: Ticket[] = [
  {
    id: "t1",
    subject: "Не пришёл код Steam Wallet",
    status: "OPEN",
    priority: "HIGH",
    category: "Платежи",
    messages: 3,
    createdAt: "2026-05-04T11:00:00Z",
    userId: "u_2",
  },
  {
    id: "t2",
    subject: "Спор по сделке #o_2",
    status: "PENDING",
    priority: "MEDIUM",
    category: "Споры",
    messages: 7,
    createdAt: "2026-05-03T10:00:00Z",
    userId: "u_1",
  },
  {
    id: "t3",
    subject: "Вопрос по выводу на крипту",
    status: "RESOLVED",
    priority: "LOW",
    category: "Кошелёк",
    messages: 5,
    createdAt: "2026-05-01T09:00:00Z",
    userId: "u_2",
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rv_1",
    authorName: "FrostMage",
    avatar: "https://avatars.githubusercontent.com/u/2?v=4",
    rating: 5,
    text: "Быстро и без проблем. Получил код через 30 секунд.",
    createdAt: "2026-05-04T12:00:00Z",
  },
  {
    id: "rv_2",
    authorName: "DragonSlayer",
    avatar: "https://avatars.githubusercontent.com/u/4?v=4",
    rating: 5,
    text: "Топ продавец, рекомендую. Уже 5-я сделка с ним.",
    createdAt: "2026-04-30T18:00:00Z",
  },
  {
    id: "rv_3",
    authorName: "NightOwl",
    avatar: "https://avatars.githubusercontent.com/u/5?v=4",
    rating: 4,
    text: "Хороший вариант, но ждал 25 минут вместо обещанных 10.",
    createdAt: "2026-04-28T20:00:00Z",
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "n_1",
    type: "ORDER",
    title: "Заказ доставлен",
    body: "Ваш заказ #o_1 успешно завершён",
    isRead: false,
    createdAt: "2026-05-05T14:30:00Z",
  },
  {
    id: "n_2",
    type: "PAYMENT",
    title: "Платёж получен",
    body: "+ 7 800 ₽ на ваш баланс",
    isRead: false,
    createdAt: "2026-05-04T16:25:00Z",
  },
  {
    id: "n_3",
    type: "REVIEW",
    title: "Новый отзыв",
    body: "Покупатель оставил отзыв 5★",
    isRead: true,
    createdAt: "2026-05-03T19:10:00Z",
  },
];

export const MOCK_FAQ = [
  {
    q: "Как работает гарантия сделки?",
    a: "Деньги покупателя замораживаются на платформе до подтверждения получения товара. Если возникает спор — модератор рассматривает обращение в течение 24 часов.",
  },
  {
    q: "Какие комиссии у платформы?",
    a: "Комиссия продавца — 5% от суммы сделки. Покупатели не платят комиссию. Вывод средств — 1% (минимум 50 ₽).",
  },
  {
    q: "Как стать верифицированным продавцом?",
    a: "Пройдите KYC (паспорт + селфи), проведите минимум 10 успешных сделок и получите средний рейтинг 4.5+.",
  },
  {
    q: "Что делать, если не пришёл товар?",
    a: "Откройте спор в карточке заказа. Модератор подключится в течение 30 минут. В большинстве случаев деньги возвращаются на баланс.",
  },
  {
    q: "Как работает автоматизация (боты)?",
    a: "Подключите свой аккаунт FunPay/Steam/Playerok через API и настройте автоответы, авто-доставку и парсинг цен.",
  },
];
